/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _player1_point_h_
#define _player1_point_h_
//---------------------------------------------------------------------------------
extern const unsigned char player1_point[];
extern const int player1_point_size;
//---------------------------------------------------------------------------------
#endif //_player1_point_h_
//---------------------------------------------------------------------------------
